/*
 * @Author: shixia.ds
 * @Date: 2021-11-23 14:29:03
 * @Description:
 */
import G6, { ModelConfig } from '@antv/g6';

const dangerous_COLOR = '#F5222D';
const WARNING_COLOR = '#FFC020';
const NORMAL_COLOR = '#3592FE';
const arrowStyleType = {
  dangerousous: {
    stroke: dangerous_COLOR,
    lineAppendWidth: 10,
    cursor: 'pointer',
    lineDash: [4, 4, 4, 4],
    lineWidth: 1,
    endArrow: {
      path: G6.Arrow.triangle(),
      fill: dangerous_COLOR,
      strokeOpacity: 0,
    },
  },
  warning: {
    stroke: WARNING_COLOR,
    lineAppendWidth: 10,
    cursor: 'pointer',
    lineDash: [4, 4, 4, 4],
    lineWidth: 1,
    endArrow: {
      path: G6.Arrow.triangle(),
      fill: WARNING_COLOR,
      strokeOpacity: 0,
    },
  },
  normal: {
    stroke: NORMAL_COLOR,
    lineAppendWidth: 10,
    cursor: 'pointer',
    lineDash: [4, 4, 4, 4],
    lineWidth: 1,
    endArrow: {
      path: G6.Arrow.triangle(),
      fill: NORMAL_COLOR,
      strokeOpacity: 0,
    },
  },
};
export const OriginData = {
  nodes: [
    { id: 'region0', nodeLabel: '0', type: 'region-node', status: 'normal', nodeType: 'region' },
    { id: 'region1', nodeLabel: '1', type: 'region-node', status: 'normal', nodeType: 'region' },
    { id: 'region2', nodeLabel: '2', type: 'region-node', status: 'warning', nodeType: 'region' },
    { id: 'region3', nodeLabel: '3', type: 'region-node', status: 'dangerous', nodeType: 'region' },
    { id: 'region4', nodeLabel: '4', type: 'region-node', status: 'normal', nodeType: 'region' },
    { id: 'region5', nodeLabel: '5', type: 'region-node', status: 'normal', nodeType: 'region' },

    { id: 'node0', nodeLabel: '0', status: 'normal', nodeRegionCode: 'region0', nodeType: 'app' },
    { id: 'node1', nodeLabel: '1', status: 'normal', nodeRegionCode: 'region1', nodeType: 'app' },
    { id: 'node2', nodeLabel: '2', status: 'warning', nodeRegionCode: 'region2', nodeType: 'app' },
    { id: 'node3', nodeLabel: '3', status: 'dangerous', nodeRegionCode: 'region3', nodeType: 'app' },
    { id: 'node4', nodeLabel: '4', status: 'normal', nodeRegionCode: 'region4', nodeType: 'app' },
    { id: 'node5', nodeLabel: '5', status: 'normal', nodeRegionCode: 'region4', nodeType: 'app' },
    { id: 'node6', nodeLabel: '6', status: 'dangerous', nodeRegionCode: 'region1', nodeType: 'app' },
    { id: 'node7', nodeLabel: '7', status: 'normal', nodeRegionCode: 'region1', nodeType: 'app' },
    { id: 'node8', nodeLabel: '8', status: 'normal', nodeRegionCode: 'region2', nodeType: 'app' },
    { id: 'node9', nodeLabel: '9', status: 'normal', nodeRegionCode: 'region2', nodeType: 'app' },
    { id: 'node10', nodeLabel: '10', status: 'normal', nodeRegionCode: 'region2', nodeType: 'app' },
    { id: 'node11', nodeLabel: '11', status: 'dangerous', nodeRegionCode: 'region2', nodeType: 'app' },
    { id: 'node12', nodeLabel: '12', status: 'normal', nodeRegionCode: 'region2', nodeType: 'app' },
    { id: 'node13', nodeLabel: '13', status: 'normal', nodeRegionCode: 'region2', nodeType: 'app' },
    { id: 'node14', nodeLabel: '14', status: 'normal', nodeRegionCode: 'region3', nodeType: 'app' },
    { id: 'node15', nodeLabel: '15', status: 'normal', nodeRegionCode: 'region3', nodeType: 'app' },
    { id: 'node16', nodeLabel: '16', status: 'normal', nodeRegionCode: 'region3', nodeType: 'app' },
    { id: 'node17', nodeLabel: '17', status: 'warning', nodeRegionCode: 'region5', nodeType: 'app' },
  ],
  edges: [
    {
      id: 'edge1',
      source: 'region0',
      target: 'region1',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      style: arrowStyleType.normal,
    },
    { source: 'region0', target: 'region2', rt: '124ms', suc: '97%', qps: '234/s', style: arrowStyleType.normal },
    { source: 'region0', target: 'region3', rt: '124ms', suc: '97%', qps: '234/s', style: arrowStyleType.normal },
    { source: 'region0', target: 'region4', rt: '124ms', suc: '97%', qps: '234/s', style: arrowStyleType.normal },
    { source: 'region0', target: 'region5', rt: '124ms', suc: '97%', qps: '234/s', style: arrowStyleType.normal },
    { source: 'region1', target: 'region4', rt: '124ms', suc: '97%', qps: '234/s', style: arrowStyleType.normal },
    { source: 'region2', target: 'region3', rt: '124ms', suc: '97%', qps: '234/s', style: arrowStyleType.normal },
    { source: 'region2', target: 'region4', rt: '124ms', suc: '97%', qps: '234/s', style: arrowStyleType.normal },

    { source: 'node0', target: 'region1', rt: '124ms', suc: '97%', qps: '234/s', style: arrowStyleType.normal },
    { source: 'node0', target: 'region2', rt: '124ms', suc: '97%', qps: '234/s', style: arrowStyleType.normal },
    { source: 'node0', target: 'region3', rt: '124ms', suc: '97%', qps: '234/s', style: arrowStyleType.normal },
    { source: 'node0', target: 'region4', rt: '124ms', suc: '97%', qps: '234/s', style: arrowStyleType.normal },
    { source: 'node0', target: 'region5', rt: '124ms', suc: '97%', qps: '234/s', style: arrowStyleType.normal },

    {
      source: 'node0',
      target: 'node1',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'warning',
      style: arrowStyleType.warning,
    },
    {
      source: 'node0',
      target: 'node2',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'dangerous',
      style: arrowStyleType.dangerousous,
    },
    {
      source: 'node0',
      target: 'node3',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node0',
      target: 'node4',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'warning',
      style: arrowStyleType.warning,
    },
    {
      source: 'node0',
      target: 'node5',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node1',
      target: 'node6',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'dangerous',
      style: arrowStyleType.dangerousous,
    },
    {
      source: 'node1',
      target: 'node7',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node2',
      target: 'node8',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node2',
      target: 'node9',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'warning',
      style: arrowStyleType.warning,
    },
    {
      source: 'node2',
      target: 'node10',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node2',
      target: 'node11',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node2',
      target: 'node12',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node2',
      target: 'node13',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'dangerous',
      style: arrowStyleType.dangerousous,
    },
    {
      source: 'node3',
      target: 'node14',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node3',
      target: 'node15',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node3',
      target: 'node16',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node8',
      target: 'node10',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node8',
      target: 'node13',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node8',
      target: 'node12',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node4',
      target: 'node5',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'normal',
      style: arrowStyleType.normal,
    },
    {
      source: 'node0',
      target: 'node17',
      rt: '124ms',
      suc: '97%',
      qps: '234/s',
      status: 'warning',
      style: arrowStyleType.warning,
    },
  ],
  combos: [],
};
