export const columns = [
    {
        title: '报告日期时间',
        dataIndex: 'reportDataTime',
        key: 'reportDataTime',
    },
    {
        title: '标本编号',
        dataIndex: 'sampleId',
        key: 'sampleId',
    },
    {
        title: '标本名称',
        dataIndex: 'sampleName',
        key: 'sampleName',
    },
    {
        title: '创建时间',
        dataIndex: 'createTime',
        key: 'createTime',
    },
    {
        title: '个人编号',
        dataIndex: 'onePersonId',
        key: 'onePersonId',
    },
    {
        title: '检查日期时间',
        dataIndex: 'examDateTime',
        key: 'examDateTime',
    },
    {
        title: '校验单据号',
        dataIndex: 'labReportNo',
        key: 'labReportNo',
    },
    {
        title: '经办时间',
        dataIndex: 'agentDateTime',
        key: 'agentDateTime',
    },
    {
        title: '就诊流水号',
        dataIndex: 'visitSeriNo',
        key: 'visitSeriNo',
    },
    {
        title: '科室编码',
        dataIndex: 'deptCode',
        key: 'deptCode',
    },
    {
        title: '科室名称',
        dataIndex: 'deptName',
        key: 'deptName',
    },
    {
        title: '医师服务编码',
        dataIndex: 'physicianServCode',
        key: 'physicianServCode',
    },
    {
        title: '医师姓名',
        dataIndex: 'physicianName',
        key: 'physicianName',
    },
    {
        title: '医院收费项目编码',
        dataIndex: 'hospChargeItemCode',
        key: 'hospChargeItemCode',
    },
    {
        title: '医院收费项目名称',
        dataIndex: 'hospChargeItemName',
        key: 'hospChargeItemName',
    },
    {
        title: '诊断编码',
        dataIndex: 'diagCode',
        key: 'diagCode',
    },
    {
        title: '诊断名称',
        dataIndex: 'diagFullName',
        key: 'diagFullName',
    },
    {
        title: '中心收费项目编码',
        dataIndex: 'projectChargeProjectCode',
        key: 'projectChargeProjectCode',
    },
    {
        title: '组织机构代码',
        dataIndex: 'orgCode',
        key: 'orgCode',
    }
]

export const tableData = [
    {
        reportDataTime: '2020-05-20',
        sampleId: 'ZSHBB178723',
        sampleName: '唾液',
        createTime: '2021-09-28 22:12:37',
        onePersonId: 'HSPN02390612',
        examDateTime: '2021-09-28',
        labReportNo: 'JYDLS2209588',
        agentDateTime: '2021-09-28 22:12:37',
        visitSeriNo: "LS1023030399",
        deptCode: 'ZH047',
        deptName: '青春期保健专业',
        physicianServCode: 'HSTF100499',
        physicianName: '毛凯',
        hospChargeItemCode: 'ZSHSF4399',
        hospChargeItemName: '采集收费',
        diagCode: "A24.4EE",
        diagFullName: "类鼻疽",
        projectChargeProjectCode: "ZSHZXSF9819",
        orgCode: 'ZHSDJHI'
    },
    {
        reportDataTime: '2020-05-24',
        sampleId: 'ZSHBB178724',
        sampleName: '粪便',
        createTime: '2021-07-17 22:09:18',
        onePersonId: 'HSPN02390509',
        examDateTime: '2021-07-17',
        labReportNo: 'JYDLS2209333',
        agentDateTime: '2021-07-17 22:09:18',
        visitSeriNo: "LS1023030318",
        deptCode: 'ZH050',
        deptName: '妇女心理卫生专业',
        physicianServCode: 'HSTF100418',
        physicianName: '夏锐泽',
        hospChargeItemCode: 'ZSHSF4318',
        hospChargeItemName: '住院收费',
        diagCode: "A18.5E4+",
        diagFullName: "葡萄膜结核",
        projectChargeProjectCode: "ZSHZXSF9738",
        orgCode: 'ZHSDJHI'
    },
    {
        reportDataTime: '2020-06-20',
        sampleId: 'ZSHBB178725',
        sampleName: '唾液',
        createTime: '2021-07-15 10:04:57',
        onePersonId: 'HSPN02390222',
        examDateTime: '2021-07-15',
        labReportNo: 'JYDLS2209241',
        agentDateTime: '2021-07-15 10:04:57',
        visitSeriNo: "LS1023030291",
        deptCode: 'ZH023',
        deptName: '老年病专业',
        physicianServCode: 'HSTF100391',
        physicianName: '姚烨华',
        hospChargeItemCode: 'ZSHSF4291',
        hospChargeItemName: '通用收费',
        diagCode: "A18.2E8",
        diagFullName: "腹腔淋巴结结核",
        projectChargeProjectCode: "ZSHZXSF9711",
        orgCode: 'ZHSDJHI'
    },
    {
        reportDataTime: '2020-06-11',
        sampleId: 'ZSHBB178726',
        sampleName: '粪便',
        createTime: '2021-07-26 13:53:14',
        onePersonId: 'HSPN02390395',
        examDateTime: '2021-07-26',
        labReportNo: 'JYDLS2209380',
        agentDateTime: '2021-07-26 13:53:14',
        visitSeriNo: "LS1023030304",
        deptCode: 'ZH036',
        deptName: '心脏移植项目',
        physicianServCode: 'HSTF100404',
        physicianName: '余锦程',
        hospChargeItemCode: 'ZSHSF4304',
        hospChargeItemName: '住院收费',
        diagCode: "A18.4E2",
        diagFullName: "皮下组织结核",
        projectChargeProjectCode: "ZSHZXSF9724",
        orgCode: 'ZHSDJHI'
    },
    {
        reportDataTime: '2020-06-18',
        sampleId: 'ZSHBB178727',
        sampleName: '唾液',
        createTime: '2020-06-16 03:43:02',
        onePersonId: 'HSPN02390377',
        examDateTime: '2020-06-16',
        labReportNo: 'JYDLS2209173',
        agentDateTime: '2020-06-16 03:43:02',
        visitSeriNo: "LS1023029911",
        deptCode: 'ZH021',
        deptName: '免疫学专业',
        physicianServCode: 'ZSHSF3911',
        physicianName: '石韩',
        hospChargeItemCode: 'ZSHSF3911',
        hospChargeItemName: '输液收费',
        diagCode: "A81.1EE",
        diagFullName: "副伤寒甲",
        projectChargeProjectCode: "ZSHZXSF9331",
        orgCode: 'ZHSDJHI'
    },
    {
        reportDataTime: '2020-06-12',
        sampleId: 'ZSHBB178728',
        sampleName: '唾液',
        createTime: '2020-06-16 03:43:02',
        onePersonId: 'HSPN02390377',
        examDateTime: '2020-06-16',
        labReportNo: 'JYDLS2209173',
        agentDateTime: '2020-06-16 03:43:02',
        visitSeriNo: "LS1023029911",
        deptCode: 'ZH021',
        deptName: '免疫学专业',
        physicianServCode: 'ZSHSF3911',
        physicianName: '石韩',
        hospChargeItemCode: 'ZSHSF3911',
        hospChargeItemName: '输液收费',
        diagCode: "A81.1EE",
        diagFullName: "副伤寒甲",
        projectChargeProjectCode: "ZSHZXSF9331",
        orgCode: 'ZHSDJHI'
    }
]

export const detailColumns = [
    {
        title: '参考值上限',
        dataIndex: 'referenceValueUp',
        key: 'referenceValueUp',
    },
    {
        title: '参考值下限',
        dataIndex: 'referenceValueDown',
        key: 'referenceValueDown',
    },
    {
        title: '创建时间',
        dataIndex: 'creatTime',
        key: 'creatTime',
    },
    {
        title: '个人编号',
        dataIndex: 'onePersonId',
        key: 'onePersonId',
    },
    {
        title: '计量单位',
        dataIndex: 'measureUnitName',
        key: 'measureUnitName',
    },
    {
        title: '检验单据号',
        dataIndex: 'labReportNo',
        key: 'labReportNo',
    },
    {
        title: '检验结果',
        dataIndex: 'labResultValue',
        key: 'labResultValue',
    },
    {
        title: '检验明细编码',
        dataIndex: 'labDetailCode',
        key: 'labDetailCode',
    },
    {
        title: '检验明细流水号',
        dataIndex: 'labDetailNo',
        key: 'labDetailNo',
    },
    {
        title: '检验明细名称',
        dataIndex: 'labDetailName',
        key: 'labDetailName',
    },
    {
        title: '经办日期',
        dataIndex: 'agentDateTime',
        key: 'agentDateTime',
    },
    {
        title: '就诊流水号',
        dataIndex: 'visitSeriNo',
        key: 'visitSeriNo',
    },
    {
        title: '异常提示',
        dataIndex: 'abnInfor',
        key: 'abnInfor',
    },
    {
        title: '组织机构代码',
        dataIndex: 'orgCode',
        key: 'orgCode',
    },
]