export default {
  检验明细表结构: [
    {
      reference_value_up: 'reference_value_down',
      检验明细: '检验明细',
      参考值上限: '参考值下限',
    },
    {
      reference_value_up: 'create_time',
      检验明细: '检验明细',
      参考值上限: '创建时间',
    },
    {
      reference_value_up: 'oneperson_id',
      检验明细: '检验明细',
      参考值上限: '个人编号',
    },
    {
      reference_value_up: 'measure_unit_name',
      检验明细: '检验明细',
      参考值上限: '计量单位',
    },
    {
      reference_value_up: 'lab_report_no',
      检验明细: '检验明细',
      参考值上限: '检验单据号',
    },
    {
      reference_value_up: 'lab_result_value',
      检验明细: '检验明细',
      参考值上限: '检验结果',
    },
    {
      reference_value_up: 'lab_detail_code',
      检验明细: '检验明细',
      参考值上限: '检验明细编码',
    },
    {
      reference_value_up: 'lab_detail_no',
      检验明细: '检验明细',
      参考值上限: '检验明细流水号',
    },
    {
      reference_value_up: 'lab_detail_name',
      检验明细: '检验明细',
      参考值上限: '检验明细名称',
    },
    {
      reference_value_up: 'agent_datetime',
      检验明细: '检验明细',
      参考值上限: '经办日期',
    },
    {
      reference_value_up: 'visit_seri_no',
      检验明细: '检验明细',
      参考值上限: '就诊流水号',
    },
    {
      reference_value_up: 'abn_infor',
      检验明细: '检验明细',
      参考值上限: '异常提示',
    },
    {
      reference_value_up: 'org_code',
      检验明细: '检验明细',
      参考值上限: '组织机构代码',
    },
  ],
  医保上传检验单表结构: [
    {
      report_datetime: 'sample_id',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '标本编号',
    },
    {
      report_datetime: 'sample_name',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '标本名称',
    },
    {
      report_datetime: 'create_time',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '创建时间',
    },
    {
      report_datetime: 'oneperson_id',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '个人编号',
    },
    {
      report_datetime: 'exam_datetime',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '检查日期时间',
    },
    {
      report_datetime: 'lab_report_no',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '检验单据号',
    },
    {
      report_datetime: 'agent_datetime',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '经办时间',
    },
    {
      report_datetime: 'visit_seri_no',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '就诊流水号',
    },
    {
      report_datetime: 'dept_code',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '科室编码',
    },
    {
      report_datetime: 'dept_name',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '科室名称',
    },
    {
      report_datetime: 'physician_serv_code',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '医师服务编码',
    },
    {
      report_datetime: 'physician_name',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '医师姓名',
    },
    {
      report_datetime: 'hosp_charge_item_code',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '医院收费项目编码',
    },
    {
      report_datetime: 'hosp_charge_item_name',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '医院收费项目名称',
    },
    {
      report_datetime: 'diag_code',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '诊断编码',
    },
    {
      report_datetime: 'diag_fullname',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '诊断名称',
    },
    {
      report_datetime: 'project_charge_project_code',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '中心收费项目编码',
    },
    {
      report_datetime: 'org_code',
      医保上传检验单: '医保上传检验单',
      报告日期时间: '组织机构代码',
    },
  ],
  数据字段集: [
    {
      报告日期时间: '组织机构代码',
      Column2: null,
      Column3: null,
      Column4: null,
      Column5: null,
    },
  ],
  医保上传检验单表数据: [
    {
      报告日期时间: '2021-11-15',
      标本编号: 'ZSHBB179224',
      标本名称: '粪便',
      创建时间: '2021-11-15 12:48:56',
      个人编号: 'HSPN32398924',
      检查日期时间: '2021-11-15',
      检验单据号: 'JYDLS3208214',
      经办时间: '2021-11-15 12:48:56',
      就诊流水号: 'LS3023892400',
      科室编码: 'ZH050',
      科室名称: '妇女心理卫生专业',
      医师服务编码: 'HSTF100502',
      医师姓名: '闻人恨竹',
      医院收费项目编码: 'ZSHSF4402',
      医院收费项目名称: '住院收费',
      诊断编码: 'A25.9EE',
      诊断名称: '鼠咬热',
      中心收费项目编码: 'ZSHZXSF9822',
      组织机构代码: 'ZHSDJHI',
    },
  ],
  仅在校验明细表数据中存在: [
    {
      参考值上限: 12.686,
      参考值下限: 3.241,
      创建时间: '2021-11-15 12:49:22',
      个人编号: 'HSPN22397233',
      计量单位: 'mg',
      检验单据号: 'JYDLS1002314',
      检验结果: '阳性',
      检验明细编码: 'ZSHJY10043',
      检验明细流水号: 'JCLS1039425',
      检验明细名称: '血清果糖胺测定（糖化血清蛋白）',
      经办日期: '2021-11-15 00:00:00',
      就诊流水号: 'LS2023892393',
      异常提示: '暂无',
      组织机构代码: 'ZHSDJHI',
    },
  ],
  交集的数据: [
    {
      报告日期时间: '2021-03-07',
      标本编号: 'ZSHBB178997',
      标本名称: '血液',
      创建时间: '2021-03-07 20:46:32',
      个人编号: 'HSPN02390470',
      检查日期时间: '2021-03-07',
      检验单据号: 'JYDLS2209402',
      经办时间: '2021-03-07 20:46:32',
      就诊流水号: 'LS1023030175',
      科室编码: 'ZH033',
      科室名称: '胸外科专业',
      医师服务编码: 'HSTF100275',
      医师姓名: '尹元驹',
      医院收费项目编码: 'ZSHSF4175',
      医院收费项目名称: '采集收费',
      诊断编码: 'A16.4E2',
      诊断名称: '声带结核',
      中心收费项目编码: 'ZSHZXSF9595',
      组织机构代码: 'ZHSDJHI',
      Column20: null,
      Column21: null,
      参考值上限: 13.973,
      参考值下限: 2.966,
      创建时间: '2021-03-07 20:49:00',
      个人编号: 'HSPN02390470',
      计量单位: 'mg',
      检验单据号: 'JYDLS2209402',
      检验结果: '阴性',
      检验明细编码: 'ZSHJY10055',
      检验明细流水号: 'JCLS1039197',
      检验明细名称: '血清丙氨酸氨基转移酶测定（ALT）',
      经办日期: '2021-03-07 00:00:00',
      就诊流水号: 'LS1023030175',
      异常提示: '暂无',
      组织机构代码: 'ZHSDJHI',
    },
  ],
};
