import React from 'react';
import {
  Dataset,
  Home,
  Report,
  Extension,
  Instructions,
  PocMaindata,
  Code,
  Refresh,
  Ability,
  Atomic,
  PocIndex,
  Diagnose,
  IcFlow,
  Exit,
  Activity,
  UserRecent,
  TableSettings,
  Detail,Time,MoreCircle,
} from '@cffe/internal-icon';

/** Icon映射 */
export const IconMap = {
  'icon-poc_index': <PocIndex />,
  'icon-home': <Home />,
  'icon-dataset': <Dataset />,
  'icon-report': <Report />,
  'icon-extension': <Extension />,
  'icon-instructions': <Instructions />,
  'icon-poc_maindata': <PocMaindata />,
  'icon-code': <Code />,
  'icon-atomic': <Atomic />,
  'icon-refresh': <Refresh />,
  'icon-ability': <Ability />,
  'icon-diagnose': <Diagnose />,
  'icon-ic_flow': <IcFlow />,
  'icon-exit': <Exit />,
  'icon-activity': <Activity />,
  'icon-userRecent': <UserRecent />,
  'icon-TableSettings': <TableSettings />,
  'icon-Detail':<Detail />,
  'icon-Time':<Time />,
  'icon-MoreCircle':<MoreCircle />,
};
