export const colorMap: any = {
    '未开始': 'magenta',
    '待流转': 'volcano',
    '待签字': 'blue',
    '调研中': 'gold',
    '设计中': 'orange',
    '待评审': 'lime',
    '评审中': 'lime',
    '待开发': 'green',
    '开发中': 'blue',
    '待开发自测': 'green',
    '待测试': 'green',
    '测试中': 'blue',
    '待回归': 'blue',
    '待发布': 'blue',
    '待验收': 'cyan',
    '验收中': 'blue',
    '已验收': 'greenblue',
    '已关闭': 'default',
    '已取消': 'default',
}
